name: alpha
on: [push]
jobs:
  test_actions_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Test private action
        run: |
          cd ./
          ls
          pwd
          java -version
          python -version
      - name: test
        id: tester
        run: bash starter.sh
      - name: Hello world actions step
        id: hello
        uses: ashthetis/my-javascript-action@main
        with:
          who-to-greet: 'ashthetis'
