name: alpha
on: [push]
jobs:
  test_actions_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Test private action
        run: |
          cd ./
          ls
          pwd
      - name: test
        id: tester
        run: bash starter.sh
