name: alpha
on: [push]
jobs:
  test_actions_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: ashthetis/action-caller@main
      - name: Test private action
        run: |
          ls ./
      - name: test
        id: tester
        run: ./starter.sh
